
name: 'CD'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      actions:
        description: 'Step'
        required: true
        default: 'PLAN'
        type: choice
        options:
        - PLAN
        - APPLY

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      TF_VAR_dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
 #     with:
  #      cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
    - name: Terraform Init
      working-directory: infra
      run: terraform init
      
    - name: Terraform Plan
      working-directory: infra
      if: github.event_name == 'push' || github.event.inputs.actions == 'PLAN'
      run: terraform plan

    - name: Terraform Apply
      working-directory: infra
      if: github.event.inputs.actions == 'APPLY'
      run: terraform apply -auto-approve
