name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '15'

    - name: Install Dependencies
      working-directory: codebase/rdicidr-0.1.0
      run: npm install

    - name: Lint
      working-directory: codebase/rdicidr-0.1.0
      run: npm run lint

    - name: Test
      working-directory: codebase/rdicidr-0.1.0
      run: CI=true npm run test

    - name: Build
      working-directory: codebase/rdicidr-0.1.0
      run: npm run build
      
    - name: Docker Login
      uses: docker/login-action@v3.7.0
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build the Docker image
      working-directory: codebase/rdicidr-0.1.0
      run: |
        docker build . -t flaviosgbr/fullstacklab:${{github.run_id}}
        docker tag flaviosgbr/fullstacklab:${{github.run_id}} flaviosgbr/fullstacklab:latest
        docker push flaviosgbr/fullstacklab:${{github.run_id}}
        docker push flaviosgbr/fullstacklab:latest
